name: Bonjour
on:
  - push
  - pull_request
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node version: "20.17.x"
      - name: Check Node Version
        run: node --version
      - name: NPM CI
        run: npm ci
      - name: Build App
        run: npm run build
      - name: List dist output
        run: ls dist/
      - name: "analyse static lint"
        run : npm run lint
